## Put comments here that give an overall description of what your
## functions do

## Write a short comment describing this function

# This function takes an invertible matrix and returns a list that contains the original matrix as well as its inverse.  
makeCacheMatrix <- function(x = matrix()) {
        inv <- NULL
        set <- function(y) {
                x   <<- y
                inv <<- NULL
        }
        get    <- function() x
        setinv <- function(inverse) inv <<- inverse
        getinv <- function() inv
        list(set = set, get = get,
             setinv = setinv,
             getinv = getinv)
}


## Write a short comment describing this function
# This function takes the list generated by the makeCacheMatrix function, and returns its inverse. If the inverse was computed before, it retrieves it from the cache.
cacheSolve <- function(x, ...) {
        m <- x$getinv()
        if(!is.null(m)) {
                message("getting cached data")
                return(m)
        }
        data <- x$get()
        m <- solve(data, ...)
        x$setinv(m)
        m
}
